/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Additive {
  'id' : bigint,
  'healthEffects' : string,
  'commonProducts' : Array<string>,
  'eNumber' : [] | [string],
  'name' : string,
  'description' : string,
  'category' : string,
  'alternatives' : Array<string>,
}
export interface _SERVICE {
  'addAdditive' : ActorMethod<
    [
      string,
      [] | [string],
      string,
      string,
      string,
      Array<string>,
      Array<string>,
    ],
    bigint
  >,
  'deleteAdditive' : ActorMethod<[bigint], boolean>,
  'filterAdditivesByCategory' : ActorMethod<[string], Array<Additive>>,
  'getAdditiveByENumber' : ActorMethod<[string], Additive>,
  'getAdditiveById' : ActorMethod<[bigint], Additive>,
  'getAllAdditives' : ActorMethod<[], Array<Additive>>,
  'parseIngredients' : ActorMethod<[string], Array<Additive>>,
  'searchAdditivesByName' : ActorMethod<[string], Array<Additive>>,
  'updateAdditive' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      string,
      string,
      string,
      Array<string>,
      Array<string>,
    ],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];