/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Additive = IDL.Record({
  'id' : IDL.Nat,
  'healthEffects' : IDL.Text,
  'commonProducts' : IDL.Vec(IDL.Text),
  'eNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'filterAdditivesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Additive)],
      ['query'],
    ),
  'getAdditiveByENumber' : IDL.Func([IDL.Text], [Additive], ['query']),
  'getAdditiveById' : IDL.Func([IDL.Nat], [Additive], ['query']),
  'getAllAdditives' : IDL.Func([], [IDL.Vec(Additive)], ['query']),
  'parseIngredients' : IDL.Func([IDL.Text], [IDL.Vec(Additive)], ['query']),
  'searchAdditivesByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Additive)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Additive = IDL.Record({
    'id' : IDL.Nat,
    'healthEffects' : IDL.Text,
    'commonProducts' : IDL.Vec(IDL.Text),
    'eNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'filterAdditivesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Additive)],
        ['query'],
      ),
    'getAdditiveByENumber' : IDL.Func([IDL.Text], [Additive], ['query']),
    'getAdditiveById' : IDL.Func([IDL.Nat], [Additive], ['query']),
    'getAllAdditives' : IDL.Func([], [IDL.Vec(Additive)], ['query']),
    'parseIngredients' : IDL.Func([IDL.Text], [IDL.Vec(Additive)], ['query']),
    'searchAdditivesByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Additive)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };